name: Testing
on:
  push:
    branches:
      - demo-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout branch
      uses: actions/checkout@v2
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.DEMO_SECRET }}
    - name: clone git
      run: git clone https://github.com/fake-orgn/new.git
    - name: do actions
      run: |
        cd $(pwd)/new
        touch hi.txt
        git add --all
        git commit -m "initial commit"
        git push origin master
