name: Testing
on:
  push:
    branches:
      - demo-branch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/workdir/demo
    steps:
    - name: checkout branch
      uses: actions/checkout@v2
    - name: check dir
      run: pwd
    - name: check dir 2
      run: pwd
    - name: get message
      run: echo "$GITHUB_CONTEXT"
