name: Testing
on:
  push:
    branches:
      - demo-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: show data
      run: ls -l
    - name: change directory
      run: pwd
    - name: Get remote git
      run: git remote -v
        
