name: Testing
on:
  push:
    branches:
      - demo-branch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work
    steps:
    - name: action checkout
      uses: actions/checkout@v2
    - name: check dir
      run: pwd
    - name: ls
      run: ls -la
    - name: get from github
      run: echo github
    - name: get message 
      run: echo ${{ github.event.head_commit.message }}
