name: Testing
on:
  push:
    branches:
      - demo-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout branch
      uses: actions/checkout@v2
    - name: make dir
      run: ls -la
        
