name: Testing
on:
  push:
    branches:
      - demo-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get remote git
      run: |
        pwd
    - name: show files
      run: ls -l
        
