name: Testing
on:
  push:
    branches:
      - demo-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Rus file
      run: |
        git config --global user.email "tmohansk@gmail.com"
        git config --global user.name "mohansai1997"
    - name: Pull repo
      run: |
        git clone https://github.com/MohanSai1997/demo.git
    - name: get data
      run: ls -l
    - name: change directory
      run: cd ./demo
    - name: feteh all branches
      run: |
        git fetch -all
        git branch fake-branch
        git checkout fake-branch
    - name: add file
      run: |
        echo "mohan" >> fake.text
        git add --all
        git commit -m "fake file added"
        git push origin master
        
