name: Testing
on:
  push:
    branches:
      - demo-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get remote git
      run: |
        git remote -v
        pwd
        cd ..
    - name: show files
      run: ls -l
        
