name: Testing
on:
  push:
    branches:
      - demo-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout branch
      uses: actions/checkout@v2
    - name: clone git
      run: git clone https://github.com/fake-orgn/new.git
    - name: set up account
      run: |
        git config --global user.email "tmohansk@gmail.com"
        git config --global user.name "Mohan Sai"
    - name: do actions
      run: |
        pwd
        cd $(pwd)/new
        touch hil
        git add --all
        git commit -m "initial commit"
        git push origin master
