name: Testing
on:
  push:
    branches:
      - demo-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout branch
      uses: actions/checkout@v2
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.DEMO_SECRET }}
    - name: add repo
      run: git remote add fake-origin https://github.com/fake-orgn/new.git
    - name: commit
      run: git commit -m "initial commit"
    - name: pus
      run: git push fake-origin master
