name: Testing
on:
  push:
    branches:
      - demo-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout branch
      uses: actions/checkout@v2
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.DEMO_SECRET }}
    - name: create branch
      run: git branch fake
    - name: push brach
      run: git push origin fake
        
