name: Testing
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull repo
      run: git clone https://github.com/MohanSai1997/demo.git
    - name: cd into repo
      run: cd demo
    - name: list the files
      run: ls
