name: Testing
on:
  push:
    branches:
      - demo-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: list files
      run: pwd
    - name: check ls
      run: ls /home/runner/work/demo/demo
